# Generated by Django 3.2.8 on 2021-10-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPlateNumber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_lot',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
