# Generated by Django 3.2.8 on 2021-12-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityalerts',
            name='license_plate',
            field=models.CharField(max_length=50),
        ),
    ]
