# Generated by Django 3.2.8 on 2021-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkPlateNumber', '0002_parking_lot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking_lot',
            name='id',
        ),
        migrations.AlterField(
            model_name='parking_lot',
            name='number',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
